### ISSUE TITLE
博客界面不错

### ISSUE THREAD

**Issue by zhaoxinjie** [shihao1010/myblog#1]
博客界面看起来很不错，文章列表中的图片是怎么弄的啊

**Comment by shihao1010** [comment]
> 博客界面看起来很不错，文章列表中的图片是怎么弄的啊

我在article模型中添加了背景图字段，在后台写文章时，可以添加pic_image，在前端界面加载就好了

**Comment by zhaoxinjie** [comment]
django是没办法用数据库存图片吗，只能上传到路径下吗。总觉得这样的话，项目文件夹越来越大，想迁移一次好麻烦

**Comment by shihao1010** [comment]
models.image不就是在数据库中存图片吗

**Comment by shihao1010** [comment]
可以存图片的base64转码

**Comment by zhaoxinjie** [comment]
因为我看到你的图片，包括文章里的图片，都存到了项目路径下upload_to='pic_img'，这样做好处是什么啊

**Comment by shihao1010** [comment]
方便管理算不算好处

**Comment by shihao1010** [comment]
我本来是想把这个图片文件夹迁移到cdn上，后来因为买不起流量放弃了。
